-- ShareSpace reference data
-- Still needs to be discussed to what reference data we want.
-- Admin panel might be used to add reference data if we want as well.

INSERT OR IGNORE INTO categories (name, description)
VALUES
  ('Electronics', 'Phones, TVs and other electronics.'),
  ('Tools', 'Power tools and hand tools.'),
  ('Gaming', 'Enter a world of adventure and exitement.'),
  ('Pets', 'Show your animal friends some love.'),
  ('Outdoor', 'Get into the great outdoors.'),
  ('Fashion', 'Find your style.'),
  ('Travel', 'Discover the world'),
  ('Home', 'Transform your space into a work of art'),
  ('Music', 'Turn it up'),
  ('Designer Goods', 'Surround yourself with luxury'),
  ('Plants', 'Transform your home into a oasis'),
  ('Cooking', 'Cook up something special'),
  ('Toys & Collectibles', 'Bring home a new friend'),
  ('Driveables', 'Drive your mood'),
  ('Real Estate', 'Find your new home'),
  ('Books', 'Read to your desire'),
  ('Health & Beauty', 'Take care of yourself'),
  ('Jewelry & Watches', 'Luxury lifestyle'),
  ('Sporting', 'Experience greatness'),
  ('Baby', 'Baby supplies'),    
  ('Everything else', 'Discover hidden gems');

INSERT OR IGNORE INTO sub_categories (name, category_id)
WITH v(name, category_name) AS (
  VALUES
    ('Smartphone',          'Electronics'),
    ('TV',                  'Electronics'),
    ('Laptop',              'Electronics'),
    ('Camera',              'Electronics'),
    ('Smart Watch',         'Electronics'),
    ('Home Electronics',    'Electronics'),
    ('Desktop Computer',    'Electronics'),
    ('Hammer',              'Tools'),
    ('Drill',               'Tools'),
    ('Saw',                 'Tools'),
    ('Lawn Mower',          'Tools'),
    ('Screwdriver',         'Tools'),
	('Console',             'Gaming'),
    ('PC Gaming',           'Gaming'),
    ('Video Game',          'Gaming'),
    ('Board Game',          'Gaming'),
    ('VR Headset',          'Gaming'),
    ('Gaming Accessory',    'Gaming'),
    ('Dog Supplies',        'Pets'),
    ('Cat Supplies',        'Pets'),
    ('Aquarium',            'Pets'),
    ('Bird Supplies',       'Pets'),
    ('Small Pet Supplies',  'Pets'),
    ('Tent',                'Outdoor'),
    ('Backpack',            'Outdoor'),
    ('Sleeping Bag',        'Outdoor'),
    ('Grill',               'Outdoor'),
    ('Camping Gear',        'Outdoor'),
    ('Clothing',            'Fashion'),
    ('Shoes',               'Fashion'),
    ('Bag',                 'Fashion'),
    ('Accessories',         'Fashion'),
    ('Sunglasses',          'Fashion'),
    ('Luggage',             'Travel'),
    ('Travel Bag',          'Travel'),
    ('Travel Accessory',    'Travel'),
    ('Camping Equipment',   'Travel'),
    ('Furniture',           'Home'),
    ('Lighting',            'Home'),
    ('Decor',               'Home'),
    ('Kitchenware',         'Home'),
    ('Appliance',           'Home'),
    ('Bedding',             'Home'),
    ('Guitar',              'Music'),
    ('Keyboard',            'Music'),
    ('Drums',               'Music'),
    ('DJ Equipment',        'Music'),
    ('Speaker',             'Music'),
    ('Microphone',          'Music'),
    ('Designer Bag',        'Designer Goods'),
    ('Designer Clothing',   'Designer Goods'),
    ('Designer Shoes',      'Designer Goods'),
    ('Designer Accessory',  'Designer Goods'),
    ('Indoor Plant',        'Plants'),
    ('Outdoor Plant',       'Plants'),
    ('Succulent',           'Plants'),
    ('Planter',             'Plants'),
    ('Garden Tool',         'Plants'),
    ('Cookware',            'Cooking'),
    ('Bakeware',            'Cooking'),
    ('Kitchen Appliance',   'Cooking'),
    ('Utensils',            'Cooking'),
    ('Tableware',           'Cooking'),
    ('Action Figure',       'Toys & Collectibles'),
    ('Building Set',        'Toys & Collectibles'),
    ('Collectible Card',    'Toys & Collectibles'),
    ('Plush Toy',           'Toys & Collectibles'),
    ('Model Kit',           'Toys & Collectibles'),
    ('Car',                 'Driveables'),
    ('Motorcycle',          'Driveables'),
    ('Scooter',             'Driveables'),
    ('E-Bike',              'Driveables'),
    ('Boat',                'Driveables'),
    ('Apartment',           'Real Estate'),
    ('House',               'Real Estate'),
    ('Room',                'Real Estate'),
    ('Office Space',        'Real Estate'),
    ('Parking Space',       'Real Estate'),
    ('Fiction',             'Books'),
    ('Non-Fiction',         'Books'),
    ('Textbook',            'Books'),
    ('Comic',               'Books'),
    ('Children''s Book',    'Books'),
    ('Skincare',            'Health & Beauty'),
    ('Makeup',              'Health & Beauty'),
    ('Hair Care',           'Health & Beauty'),
    ('Fragrance',           'Health & Beauty'),
    ('Wellness Device',     'Health & Beauty'),
    ('Watch',               'Jewelry & Watches'),
    ('Ring',                'Jewelry & Watches'),
    ('Necklace',            'Jewelry & Watches'),
    ('Bracelet',            'Jewelry & Watches'),
    ('Earrings',            'Jewelry & Watches'),
    ('Fitness Equipment',   'Sporting'),
    ('Ball Sports',         'Sporting'),
    ('Water Sports',        'Sporting'),
    ('Winter Sports',       'Sporting'),
    ('Cycling',             'Sporting'),
    ('Stroller',            'Baby'),
    ('Car Seat',            'Baby'),
    ('Crib',                'Baby'),
    ('Baby Carrier',        'Baby'),
    ('Baby Toys',           'Baby')
)
SELECT v.name, c.id
FROM v
JOIN categories c ON c.name = v.category_name;

-- Roles
INSERT INTO roles (name) SELECT 'lender' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'lender');
INSERT INTO roles (name) SELECT 'renter' WHERE NOT EXISTS (SELECT 1 FROM roles WHERE name = 'renter');

